server:
  port: 8585

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: pos

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"
    file:    "%d{yyyy-MM-dd HH:mm:ss,SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.springframework: ERROR
    com.ntapia.pos: DEBUG
  file: logs/pos.log
